services:
  api-envio:
    build: ./api_envio
    ports:
      - "3000:3000"
    depends_on:
      - db

  api-recebimento:
    build: ./api_recebimento
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cadastros_db
    ports:
      - "5432:5432"
    volumes:
      - ./banco-dados/init_tables.sql:/docker-entrypoint-initdb.d/init_tables.sql
      - pgdata:/var/lib/postgresql/data

  listador-cadastros:
    build: ./listador_cadastros
    ports:
      - "3002:80"
    depends_on:
      - api-recebimento

  front-end:
    build: ./front_end
    ports:
      - "3003:3000"

volumes:
  pgdata:
    driver: local
